version: '3'

services:
        rp:
                image: nginx:1.16.1-alpine
                volumes:
                        - "./default.conf:/etc/nginx/conf.d/default.conf"
                        - "./src/main/stampo/static:/static"
                        - "./target/lavagna/help:/help"
                ports:
                        - "81:80"
                        - "8081:8081"
        db:
                image: mysql:5.7
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: 123
                volumes:
                        - "db_local_store:/var/lib/mysql"

        lavagna:
                image: lavagna
                restart: always
                ports:
                        - 8080:8080

volumes:
        db_local_store:
