version: '3'

services:
        db:
                image: mysql:5.7
                command: --default-authentication-plugin=mysql_native_password
                environment:
                        MYSQL_ROOT_PASSWORD: 123
                restart: always
                volumes:
                        - "./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
                        - "db_local_store:/var/lib/mysql"
        lavagna:
                image: lavagna
                restart: always
                depends_on:
                        - db
                ports:
                        - 8080:8080

volumes:
        db_local_store:
